### ISSUE TITLE
"An error was encountered" when trying to render

### ISSUE THREAD

**Issue by kannes** [CMU-CREATE-Lab/timemachine-creator#4]
I am on Archlinux.

x264 0.159.2999 296494a
ffmpeg version n4.2.3

I did:
```
git clone https://github.com/CMU-CREATE-Lab/timemachine-creator.git
cd timemachine-creator/tilestacktool
make
cd ../tmc
qmake-qt4
make
```

Then I ran `./tmc`. Added some images, clicked "Create Time Machine" and chose `/tmp/test/test.timemachine` as output.

The process fails with a red "An error was encountered" message at 0.0% progress. The terminal only shows some ExifErrs (about tag 513) which should not be an issue I think.

Any idea what might be wrong?

**Comment by kannes** [comment]
`strace` hinted at `/tmp/test/test.timemachine/tm.log` not being accessible so I checked the directory. These

```
./test/test.timemachine.tmp-236452-80-1590959261
./test/test.tmc
./test/test.tmc/0300-tilestacks
./test/test.tmc/0300-tilestacks/r.json
./test/test.tmc/definition.tmc
```

Looks like the name of the `.timemachine` directory has been created in a different format than what the tool expects.

**Comment by kannes** [comment]
Nope, I let it fail once, then renamed the directory to `test.timemachine` and clicked "Retry". It immediately failed again but the log was created now, woohoo!

```
[DEBUG] 2020-05-31 23:15:26 invokeRubySubprocess: 
[DEBUG] 2020-05-31 23:15:26 /tmp/timemachine-creator/ct/ct.rb 
[DEBUG] 2020-05-31 23:15:26 -j 
[DEBUG] 2020-05-31 23:15:26 2 
[DEBUG] 2020-05-31 23:15:26 /tmp/test/test.tmc/definition.tmc 
[DEBUG] 2020-05-31 23:15:26 /tmp/test/test.timemachine 
[DEBUG] 2020-05-31 23:15:26 "Invoking ruby with path: /usr/bin/ruby" 
[DEBUG] 2020-05-31 23:15:26 Found tilestacktool at /tmp/timemachine-creator/tilestacktool/tilestacktoo 
[DEBUG] 2020-05-31 23:15:26 Could not find stitch in default installation path: /tmp/timemachine-creator/ct/../gigapan-*.*.*-linux/stitc 
[DEBUG] 2020-05-31 23:15:26 Found explorer sources at /tmp/timemachine-creator/timemachine-viewe 
[DEBUG] 2020-05-31 23:15:26 Reading /tmp/test/test.tmc/definition.tm 
[DEBUG] 2020-05-31 23:15:26 /tmp/timemachine-creator/ct/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecate 
[DEBUG] 2020-05-31 23:15:26 Store is /tmp/test/test.tm 
[DEBUG] 2020-05-31 23:15:26 0.2 gigapixels total video conten 
[DEBUG] 2020-05-31 23:15:26 26 frame 
[DEBUG] 2020-05-31 23:15:26 6.1 megapixels per frame (5621px x 1080px 
[DEBUG] 2020-05-31 23:15:26 Estimated final space required: 200.0 M 
[DEBUG] 2020-05-31 23:15:26 /usr/lib/ruby/2.7.0/open-uri.rb:21:in `initialize': No such file or directory @ rb_sysopen - /tmp/timemachine-creator/timemachine-viewer/templates/player_template.html (Errno::ENOENT 
[DEBUG] 2020-05-31 23:15:26 	from /usr/lib/ruby/2.7.0/open-uri.rb:21:in `open 
[DEBUG] 2020-05-31 23:15:26 	from /usr/lib/ruby/2.7.0/open-uri.rb:21:in `open 
[DEBUG] 2020-05-31 23:15:26 	from /tmp/timemachine-creator/ct/ct.rb:214:in `read_file 
[DEBUG] 2020-05-31 23:15:26 	from /tmp/timemachine-creator/ct/ct.rb:30:in `include_ajax_file 
[DEBUG] 2020-05-31 23:15:26 	from /tmp/timemachine-creator/ct/ct.rb:1251:in `initialize 
[DEBUG] 2020-05-31 23:15:26 	from /tmp/timemachine-creator/ct/ct.rb:1972:in `new 
[DEBUG] 2020-05-31 23:15:26 	from /tmp/timemachine-creator/ct/ct.rb:1972:in `block in <main> 
[DEBUG] 2020-05-31 23:15:26 	from /tmp/timemachine-creator/ct/ct.rb:1971:in `times 
[DEBUG] 2020-05-31 23:15:26 	from /tmp/timemachine-creator/ct/ct.rb:1971:in `<main> 
```

So `timemachine-viewer/templates/player_template.html` is missing in the cloned repo directory. And that is because I did not use `--recursive` when cloning. I will try again...


PS: Looks like the last character of each line is cut off.

**Comment by kannes** [comment]
Success!
